# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8d10c65ed720dc28cd771c0596ca78255d4c302f686e245a09ce61657d47b8d6341a1b40b7df17c73e6caec2485c4dff0544937854ee53764d5cab1e7d34bc

test:
  secret_key_base: a96ded78b1d5b5b78b9d4f11a14be189a0624d3e53ba7acc97d9567815b149971138ff025f539e0fbe5f49a3e36d111588e75d4e2ef57f770633ce18255d626b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
